/**
 * Emits src/export/fonts.embedded.ts — the @font-face rules with woff2 payloads
 * inlined as data: URIs.
 *
 * This module is DYNAMICALLY IMPORTED on the export path only. It must never
 * reach the app bundle: the payload is ~360 KB and only the rasteriser and SVG
 * emitter need it, because a cloned/detached DOM cannot resolve relative font
 * URLs reliably and the SVG output has to be self-contained.
 */
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const FONT_DIR = path.join(ROOT, 'public/assets/fonts');
const CSS_IN = path.join(ROOT, 'src/styles/fonts.css');
const OUT = path.join(ROOT, 'src/export/fonts.embedded.ts');

async function run() {
  const css = await readFile(CSS_IN, 'utf8');
  const files = (await readdir(FONT_DIR)).filter((f) => f.endsWith('.woff2'));

  const cache = new Map();
  for (const f of files) {
    const buf = await readFile(path.join(FONT_DIR, f));
    cache.set(f, buf.toString('base64'));
  }

  let bytes = 0;
  const embedded = css.replace(
    /url\('\/assets\/fonts\/([^']+)'\)/g,
    (whole, file) => {
      const b64 = cache.get(file);
      if (!b64) throw new Error(`fonts.css references missing file: ${file}`);
      bytes += b64.length;
      return `url('data:font/woff2;base64,${b64}')`;
    },
  );

  await mkdir(path.dirname(OUT), { recursive: true });
  const ts = `/**
 * GENERATED by scripts/embed-fonts.mjs — do not edit by hand.
 *
 * Self-contained @font-face CSS with woff2 inlined as data: URIs, for the
 * export pipeline only. Import this DYNAMICALLY so it stays out of the app
 * bundle:
 *
 *   const { EMBEDDED_FONT_CSS } = await import('@/export/fonts.embedded');
 */

export const EMBEDDED_FONT_CSS = ${JSON.stringify(embedded)};

/** Approximate decoded payload size, for the export console's size estimate. */
export const EMBEDDED_FONT_BYTES = ${Math.round((bytes * 3) / 4)};
`;

  await writeFile(OUT, ts, 'utf8');
  console.log(
    `embed-fonts: wrote ${path.relative(ROOT, OUT)} (${(ts.length / 1024).toFixed(0)} KB source, ~${(
      (bytes * 3) / 4 / 1024
    ).toFixed(0)} KB fonts)`,
  );
}

run().catch((err) => {
  console.error('embed-fonts failed:', err.message);
  process.exit(1);
});
