/**
 * Downloads the three Keel typefaces from Google Fonts as woff2 and writes
 * src/styles/fonts.css with the real unicode-range per subset.
 *
 * Fonts are self-hosted deliberately: the SVG and PDF renderers do not share
 * the DOM's font context and need stable, unhashed family names. See README.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const FONT_DIR = path.join(ROOT, 'public/assets/fonts');
const CSS_OUT = path.join(ROOT, 'src/styles/fonts.css');

// A modern-Chrome UA is what makes Google serve woff2 + variable axes.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/** Only these subsets ship; anything else bloats the export-time base64 payload. */
const SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  {
    family: 'Newsreader',
    // variable: optical size 6..72, weight 200..800
    query: 'Newsreader:opsz,wght@6..72,200..800',
    slug: 'newsreader',
    variable: true,
  },
  {
    family: 'Hanken Grotesk',
    query: 'Hanken+Grotesk:wght@100..900',
    slug: 'hanken-grotesk',
    variable: true,
  },
  {
    family: 'JetBrains Mono',
    query: 'JetBrains+Mono:wght@400;500',
    slug: 'jetbrains-mono',
    variable: false,
  },
];

/**
 * Google emits one @font-face per subset, preceded by a `/* subset *​/` comment.
 * We parse them into structured records so the generated CSS keeps the exact
 * unicode-range Google computed rather than a guess.
 */
function parseFaces(css) {
  const faces = [];
  const blockRe = /\/\*\s*([\w-\[\]]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = blockRe.exec(css))) {
    const [, subset, body] = m;
    const pick = (prop) => {
      const r = new RegExp(`${prop}\\s*:\\s*([^;]+);`).exec(body);
      return r ? r[1].trim() : null;
    };
    const url = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/.exec(body);
    if (!url) continue;
    faces.push({
      subset,
      url: url[1],
      style: pick('font-style') ?? 'normal',
      weight: pick('font-weight') ?? '400',
      stretch: pick('font-stretch'),
      unicodeRange: pick('unicode-range'),
    });
  }
  return faces;
}

async function fetchWithRetry(url, init, attempts = 4) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, init);
      if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
      return res;
    } catch (err) {
      lastErr = err;
      if (i < attempts - 1) await new Promise((r) => setTimeout(r, 1000 * (i + 1)));
    }
  }
  throw lastErr;
}

async function run() {
  await mkdir(FONT_DIR, { recursive: true });
  const out = [];

  out.push('/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand. */');
  out.push('/* Run `npm run assets` to regenerate. Fonts are SIL Open Font License 1.1. */');
  out.push('');

  for (const fam of FAMILIES) {
    const cssUrl = `https://fonts.googleapis.com/css2?family=${fam.query}&display=block`;
    const res = await fetchWithRetry(cssUrl, { headers: { 'User-Agent': UA } });
    const css = await res.text();
    const faces = parseFaces(css).filter((f) => SUBSETS.has(f.subset));

    if (faces.length === 0) {
      throw new Error(`No usable faces parsed for ${fam.family}. Google CSS shape may have changed.`);
    }

    for (const face of faces) {
      // Static families repeat the same subset per weight; keep weight in the name.
      const weightTag = fam.variable ? 'var' : face.weight;
      const file = `${fam.slug}-${weightTag}-${face.subset}.woff2`;
      const dest = path.join(FONT_DIR, file);

      if (!existsSync(dest)) {
        const bin = await fetchWithRetry(face.url, { headers: { 'User-Agent': UA } });
        await writeFile(dest, Buffer.from(await bin.arrayBuffer()));
        console.log(`  downloaded ${file}`);
      } else {
        console.log(`  cached     ${file}`);
      }

      out.push('@font-face {');
      out.push(`  font-family: '${fam.family}';`);
      out.push(`  font-style: ${face.style};`);
      out.push(`  font-weight: ${face.weight};`);
      if (face.stretch) out.push(`  font-stretch: ${face.stretch};`);
      // block, not swap: a swapped fallback would silently rasterise into exports.
      out.push('  font-display: block;');
      out.push(`  src: url('/assets/fonts/${file}') format('woff2');`);
      if (face.unicodeRange) out.push(`  unicode-range: ${face.unicodeRange};`);
      out.push('}');
      out.push('');
    }
    console.log(`${fam.family}: ${faces.length} face(s)`);
  }

  await writeFile(CSS_OUT, out.join('\n'), 'utf8');
  console.log(`\nwrote ${path.relative(ROOT, CSS_OUT)}`);
}

run().catch((err) => {
  console.error('fetch-fonts failed:', err.message);
  process.exit(1);
});
